services:
  web:
    build: https://github.com/Chikseen/vivis.git#master:vivis
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.vivis.rule=Host(`vivis.gallery`,`www.vivis.gallery`)
      - traefik.http.routers.vivis.entrypoints=https
      - traefik.http.routers.vivis.tls=true
      - traefik.http.routers.vivis.middlewares=external-secure,vivis-redirect
      - traefik.http.middlewares.vivis-redirect.redirectregex.regex=https://www\.vivis\.gallery
      - traefik.http.middlewares.vivis-redirect.redirectregex.replacement=https://vivis.gallery
    networks:
      - proxy
    restart: always

  dev:
    build: https://github.com/Chikseen/vivis.git#dev:vivis
    ports:
      - 3001:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.vivis-dev.rule=Host(`dev.vivis.gallery`,`www.dev.vivis.gallery`)
      - traefik.http.routers.vivis-dev.entrypoints=https
      - traefik.http.routers.vivis-dev.tls=true
      - traefik.http.routers.vivis-dev.middlewares=external-secure,vivis-dev-redirect
      - traefik.http.middlewares.vivis-dev-redirect.redirectregex.regex=https://www\dev.vivis\.gallery
      - traefik.http.middlewares.vivis-dev-redirect.redirectregex.replacement=https://dev.vivis.gallery
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true