export default (nuxtConfig) => ({
    ready: () => {
        const ColorThief = require("colorthief");
        const fs = require('fs');

        console.log("start");

        // Current Workaround will change soon

        const img = __dirname + "/../assets/Images/TestImgs/Hund_Dig.jpg";
        console.log(img);

        ColorThief.getColor(img, 2)
            .then((color) => {
                console.log(color);
                fs.writeFileSync(__dirname + "/../assets/styles/autoGenerated/mainImg.scss", `$mainColor: rgb(${color.join(',')})`)
            })
            .catch((err) => {
                console.log(err);
            });

        ColorThief.getPalette(img, 2, 2)
            .then((palette) => {
                console.log(palette);
            })
            .catch((err) => {
                console.log(err);
            });
    },
});