name: Node.js CI

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16.x'
      - run: docker-compose up -d --build